# name of the program (Minix service)
PROG=proj 

.PATH: ${.CURDIR}/devices/

# source code files to be compiled
SRCS = proj.c rtc.c kbd.c timer.c video.c mouse.c game.c player.c background.c ball.c player2.c game_score.c menu.c pause.c

# additional compilation flags
# "-Wall -Wextra -Werror -I . -std=c11 -Wno-unused-parameter" are already set
CPPFLAGS += -pedantic -DLAB3

# list of library dependencies (for Lab 2, only LCF library)
DPADD += ${LIBLCF}
LDADD += -llcf

# include LCOM's makefile that does all the "heavy lifting"
.include <minix.lcom.mk>
