#ifndef XPMS_H
#define XPMS_H

#include "xpms/player1/move/move1.xpm"
#include "xpms/player1/move/move2.xpm"
#include "xpms/player1/move/move1_rev.xpm"
#include "xpms/player1/move/move2_rev.xpm"
#include "xpms/player1/hit/hit1.xpm"
#include "xpms/player1/hit/hit1_rev.xpm"
#include "xpms/player1/hit/hit2.xpm"
#include "xpms/player1/hit/hit2_rev.xpm"
#include "xpms/player1/hit/hit3.xpm"
#include "xpms/player1/hit/hit3_rev.xpm"
#include "xpms/player1/hit/hit4.xpm"
#include "xpms/player1/hit/hit4_rev.xpm"
#include "xpms/player1/start/start1.xpm"
#include "xpms/player1/start/start2.xpm"
#include "xpms/player1/start/start3.xpm"
#include "xpms/player1/start/start4.xpm"
#include "xpms/player1/start/start5.xpm"
#include "xpms/player1/start/start6.xpm"
#include "xpms/player1/start/start1_rev.xpm"
#include "xpms/player1/start/start2_rev.xpm"
#include "xpms/player1/start/start3_rev.xpm"
#include "xpms/player1/start/start4_rev.xpm"
#include "xpms/player1/start/start5_rev.xpm"
#include "xpms/player1/start/start6_rev.xpm"

#include "xpms/player2/hit/hit1_2.xpm"
#include "xpms/player2/hit/hit1_2_rev.xpm"
#include "xpms/player2/hit/hit2_2.xpm"
#include "xpms/player2/hit/hit2_2_rev.xpm"
#include "xpms/player2/move/move1_2.xpm"
#include "xpms/player2/move/move1_2_rev.xpm"
#include "xpms/player2/move/move2_2.xpm"
#include "xpms/player2/move/move2_2_rev.xpm"
#include "xpms/player2/start/start1_2.xpm"
#include "xpms/player2/start/start1_2_rev.xpm"
#include "xpms/player2/start/start2_2.xpm"
#include "xpms/player2/start/start2_2_rev.xpm"
#include "xpms/player2/start/start3_2.xpm"
#include "xpms/player2/start/start3_2_rev.xpm"

#include "xpms/Court_rec.xpm"

#include "xpms/ball/small_ball.xpm"
#include "xpms/ball/medium_ball.xpm"
#include "xpms/ball/large_ball.xpm"
#include "xpms/ball/very_large_ball.xpm"

#include "xpms/res/p1.xpm"
#include "xpms/res/p2.xpm"
#include "xpms/res/0.xpm"
#include "xpms/res/1.xpm"
#include "xpms/res/2.xpm"
#include "xpms/res/3.xpm"
#include "xpms/res/4.xpm"
#include "xpms/res/5.xpm"
#include "xpms/res/6.xpm"
#include "xpms/res/7.xpm"
#include "xpms/res/8.xpm"
#include "xpms/res/9.xpm"

#include "xpms/cursor/cursor.xpm"

#include "xpms/menu/title.xpm"
#include "xpms/menu/quit.xpm"
#include "xpms/menu/quit_hover.xpm"
#include "xpms/menu/start.xpm"
#include "xpms/menu/start_hover.xpm"

#endif
